[profile.default]
solc = "0.8.27"
src = "constracts/src"
out = "out"
libs = ["contracts/lib"]
bytecode_hash = "none"
optimizer = true
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
