name: Build and Deploy Frontnd
on: 
  push:
    branches: [main]
    paths:
      - frontend/**
  workflow_run:
    workflows: [Build and Publish SDK NPM Package]
    types:
      - completed

permissions:
  contents: write

jobs:
  build-and-deploy-frontend:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: NPM Install and Build
        run: |
          cd frontend
          npm config set @mnrgreg:registry=https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}
          npm install @mnrgreg/transfer-scheduler-sdk
          npm run build

      - name: Deploy Frontend
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist
          branch: gh-pages