name: Contract tests
on: 
  push:
    # paths:
    #   - contracts/**
    #   - test/**

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run tests
        run: |
          tree ./contracts -L 3
          forge test -vvvvv --fork-url https://sepolia.drpc.org

      - name: Run snapshot
        run: forge snapshot